/**
 * GENERATED FILE — do not edit by hand. Regenerate with:
 *   pnpm tsx scripts/build-iso-lookup.ts
 *
 * iso3 → French display name, for map labels (GeoMap's documented prop API,
 * brief §8.3, has no names prop — this is its label text source instead of
 * a DB round-trip from a client component). Source of truth is still
 * scripts/data/countries.fr.json; this is a small derived copy.
 */

export const COUNTRY_NAME_FR: Readonly<Record<string, string>> = {
  AFG: "Afghanistan",
  AGO: "Angola",
  ALB: "Albanie",
  AND: "Andorre",
  ARE: "Émirats arabes unis",
  ARG: "Argentine",
  ARM: "Arménie",
  ATG: "Antigua-et-Barbuda",
  AUS: "Australie",
  AUT: "Autriche",
  AZE: "Azerbaïdjan",
  BDI: "Burundi",
  BEL: "Belgique",
  BEN: "Bénin",
  BFA: "Burkina Faso",
  BGD: "Bangladesh",
  BGR: "Bulgarie",
  BHR: "Bahreïn",
  BHS: "Bahamas",
  BIH: "Bosnie-Herzégovine",
  BLR: "Biélorussie",
  BLZ: "Belize",
  BOL: "Bolivie",
  BRA: "Brésil",
  BRB: "Barbade",
  BRN: "Brunei",
  BTN: "Bhoutan",
  BWA: "Botswana",
  CAF: "République centrafricaine",
  CAN: "Canada",
  CHE: "Suisse",
  CHL: "Chili",
  CHN: "Chine",
  CIV: "Côte d'Ivoire",
  CMR: "Cameroun",
  COD: "République démocratique du Congo",
  COG: "Congo",
  COK: "Îles Cook",
  COL: "Colombie",
  COM: "Comores",
  CPV: "Cap-Vert",
  CRI: "Costa Rica",
  CUB: "Cuba",
  CYP: "Chypre",
  CZE: "Tchéquie",
  DEU: "Allemagne",
  DJI: "Djibouti",
  DMA: "Dominique",
  DNK: "Danemark",
  DOM: "République dominicaine",
  DZA: "Algérie",
  ECU: "Équateur",
  EGY: "Égypte",
  ERI: "Érythrée",
  ESP: "Espagne",
  EST: "Estonie",
  ETH: "Éthiopie",
  FIN: "Finlande",
  FJI: "Fidji",
  FRA: "France",
  FSM: "Micronésie",
  GAB: "Gabon",
  GBR: "Royaume-Uni",
  GEO: "Géorgie",
  GHA: "Ghana",
  GIN: "Guinée",
  GMB: "Gambie",
  GNB: "Guinée-Bissau",
  GNQ: "Guinée équatoriale",
  GRC: "Grèce",
  GRD: "Grenade",
  GTM: "Guatemala",
  GUY: "Guyana",
  HND: "Honduras",
  HRV: "Croatie",
  HTI: "Haïti",
  HUN: "Hongrie",
  IDN: "Indonésie",
  IND: "Inde",
  IRL: "Irlande",
  IRN: "Iran",
  IRQ: "Irak",
  ISL: "Islande",
  ISR: "Israël",
  ITA: "Italie",
  JAM: "Jamaïque",
  JOR: "Jordanie",
  JPN: "Japon",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KGZ: "Kirghizistan",
  KHM: "Cambodge",
  KIR: "Kiribati",
  KNA: "Saint-Christophe-et-Niévès",
  KOR: "Corée du Sud",
  KWT: "Koweït",
  LAO: "Laos",
  LBN: "Liban",
  LBR: "Liberia",
  LBY: "Libye",
  LCA: "Sainte-Lucie",
  LIE: "Liechtenstein",
  LKA: "Sri Lanka",
  LSO: "Lesotho",
  LTU: "Lituanie",
  LUX: "Luxembourg",
  LVA: "Lettonie",
  MAR: "Maroc",
  MCO: "Monaco",
  MDA: "Moldavie",
  MDG: "Madagascar",
  MDV: "Maldives",
  MEX: "Mexique",
  MHL: "Îles Marshall",
  MKD: "Macédoine du Nord",
  MLI: "Mali",
  MLT: "Malte",
  MMR: "Myanmar",
  MNE: "Monténégro",
  MNG: "Mongolie",
  MOZ: "Mozambique",
  MRT: "Mauritanie",
  MUS: "Maurice",
  MWI: "Malawi",
  MYS: "Malaisie",
  NAM: "Namibie",
  NER: "Niger",
  NGA: "Nigeria",
  NIC: "Nicaragua",
  NIU: "Niue",
  NLD: "Pays-Bas",
  NOR: "Norvège",
  NPL: "Népal",
  NRU: "Nauru",
  NZL: "Nouvelle-Zélande",
  OMN: "Oman",
  PAK: "Pakistan",
  PAN: "Panama",
  PER: "Pérou",
  PHL: "Philippines",
  PLW: "Palaos",
  PNG: "Papouasie-Nouvelle-Guinée",
  POL: "Pologne",
  PRK: "Corée du Nord",
  PRT: "Portugal",
  PRY: "Paraguay",
  PSE: "État de Palestine",
  QAT: "Qatar",
  ROU: "Roumanie",
  RUS: "Russie",
  RWA: "Rwanda",
  SAU: "Arabie saoudite",
  SDN: "Soudan",
  SEN: "Sénégal",
  SGP: "Singapour",
  SLB: "Îles Salomon",
  SLE: "Sierra Leone",
  SLV: "Salvador",
  SMR: "Saint-Marin",
  SOM: "Somalie",
  SRB: "Serbie",
  SSD: "Soudan du Sud",
  STP: "Sao Tomé-et-Principe",
  SUR: "Suriname",
  SVK: "Slovaquie",
  SVN: "Slovénie",
  SWE: "Suède",
  SWZ: "Eswatini",
  SYC: "Seychelles",
  SYR: "Syrie",
  TCD: "Tchad",
  TGO: "Togo",
  THA: "Thaïlande",
  TJK: "Tadjikistan",
  TKM: "Turkménistan",
  TLS: "Timor oriental",
  TON: "Tonga",
  TTO: "Trinité-et-Tobago",
  TUN: "Tunisie",
  TUR: "Turquie",
  TUV: "Tuvalu",
  TWN: "Taïwan",
  TZA: "Tanzanie",
  UGA: "Ouganda",
  UKR: "Ukraine",
  URY: "Uruguay",
  USA: "États-Unis",
  UZB: "Ouzbékistan",
  VAT: "Vatican",
  VCT: "Saint-Vincent-et-les-Grenadines",
  VEN: "Venezuela",
  VNM: "Vietnam",
  VUT: "Vanuatu",
  WSM: "Samoa",
  YEM: "Yémen",
  ZAF: "Afrique du Sud",
  ZMB: "Zambie",
  ZWE: "Zimbabwe",
};
