import { mkdir, writeFile, readFile, unlink } from "node:fs/promises";
import path from "node:path";
import { ulid } from "ulid";

/**
 * Files live on disk under UPLOAD_DIR (a Railway persistent volume in
 * production), never under public/ — served only through the authenticated
 * /media/[id] route. Defaults to ./.uploads locally. Brief §15.
 */
export function getUploadDir(): string {
  return process.env["UPLOAD_DIR"]?.trim() || path.resolve(process.cwd(), ".uploads");
}

const EXT_BY_MIME: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

export const ACCEPTED_IMAGE_MIME_TYPES = Object.keys(EXT_BY_MIME);
export const MAX_UPLOAD_BYTES = 8 * 1024 * 1024; // 8MB — plenty above the client's 1600px re-encode

export async function saveUpload(
  buffer: Buffer,
  mime: string,
): Promise<{ filename: string; sizeBytes: number }> {
  const dir = getUploadDir();
  await mkdir(dir, { recursive: true });
  const ext = EXT_BY_MIME[mime] ?? "bin";
  const filename = `${ulid()}.${ext}`;
  await writeFile(path.join(dir, filename), buffer);
  return { filename, sizeBytes: buffer.byteLength };
}

export async function readUpload(filename: string): Promise<Buffer> {
  const dir = getUploadDir();
  const resolved = path.resolve(dir, filename);
  // Guard against a filename escaping the upload directory (path traversal) —
  // filenames are always ulid-generated by us, but never trust a DB round-trip blindly.
  if (!resolved.startsWith(path.resolve(dir))) {
    throw new Error("Invalid upload path");
  }
  return readFile(resolved);
}

/** Admin media deletion (Phase 10) — the DB row is the source of truth for "in use", so
 *  callers must check that before calling this; a missing file is not an error (ENOENT). */
export async function deleteUpload(filename: string): Promise<void> {
  const dir = getUploadDir();
  const resolved = path.resolve(dir, filename);
  if (!resolved.startsWith(path.resolve(dir))) {
    throw new Error("Invalid upload path");
  }
  try {
    await unlink(resolved);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
}
