/**
 * Regenerates scripts/data/imported-questions.fr.json FROM the database.
 *
 * The problem this solves: the file was a one-way seed input, so the moment anyone
 * edited a question in the app — a difficulty, a wording, a choice — the file no
 * longer described reality. And since the seed skips prompts that already exist
 * (deliberately: it must never clobber a human's edit), re-running it did not
 * realign anything. A backup that silently stops matching what it backs up is not
 * a backup.
 *
 * So the direction is fixed rather than the symptom. The app is the live truth;
 * this file is its export. Edit questions wherever you like, run this before
 * committing, and the file matches again. If the database is ever wiped,
 * seed-imported-questions.ts rebuilds from it.
 *
 * Only round-trippable types are exported: mcq and open. `geo` is generated by
 * seed-geo-full.ts from the country data and would be duplicated here; `image` and
 * `sort` can carry uploaded media, which lives in UPLOAD_DIR and cannot travel in a
 * JSON file — exporting them would produce a record that restores wrong.
 *
 * Run: pnpm tsx scripts/export-questions.ts            (write)
 *      pnpm tsx scripts/export-questions.ts --check    (report drift, write nothing)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { asc, eq, inArray } from "drizzle-orm";
import { db, client } from "@/server/db";
import { questions, questionChoices, questionOpenAnswers, categories } from "@/server/db/schema";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FILE = path.resolve(__dirname, "data/imported-questions.fr.json");

/** Types this file can faithfully restore. See the header for why the others are out. */
const EXPORTABLE = ["mcq", "open"] as const;

interface Exported {
  categorie: string;
  difficulte: number;
  enonce: string;
  /** Only present when it isn't "published" — see the comment at the assignment. */
  statut?: "draft" | "archived";
  choix?: Array<{ texte: string; correct: boolean }>;
  reponses?: string[];
  explication?: string;
}

function canonical(q: Exported): string {
  const ordered: Record<string, unknown> = {
    categorie: q.categorie,
    difficulte: q.difficulte,
    enonce: q.enonce,
  };
  if (q.statut) ordered.statut = q.statut;
  if (q.choix) ordered.choix = q.choix.map((c) => ({ texte: c.texte, correct: c.correct }));
  if (q.reponses) ordered.reponses = q.reponses;
  if (q.explication) ordered.explication = q.explication;
  return JSON.stringify(ordered);
}

async function main() {
  const check = process.argv.includes("--check");

  const rows = await db
    .select({
      id: questions.id,
      type: questions.type,
      prompt: questions.prompt,
      difficulty: questions.difficulty,
      explanation: questions.explanation,
      status: questions.status,
      category: categories.name,
    })
    .from(questions)
    .innerJoin(categories, eq(categories.id, questions.categoryId))
    .where(inArray(questions.type, [...EXPORTABLE]))
    .orderBy(asc(categories.name), asc(questions.difficulty), asc(questions.prompt));

  const exported: Exported[] = [];
  for (const row of rows) {
    // Archived questions are kept in the export: they were authored work, and
    // dropping them here would mean a restore silently loses them. Their status
    // travels with them, though — without it, a restore would republish something
    // a human had deliberately taken out of rotation, and the archiving would look
    // like it had silently reverted itself. Omitted when published, which is the
    // overwhelming majority, so the file stays quiet.
    const base: Exported = {
      categorie: row.category,
      difficulte: row.difficulty,
      enonce: row.prompt,
      ...(row.status === "published" ? {} : { statut: row.status }),
    };
    if (row.type === "mcq") {
      const choices = await db
        .select({ label: questionChoices.label, isCorrect: questionChoices.isCorrect })
        .from(questionChoices)
        .where(eq(questionChoices.questionId, row.id))
        .orderBy(asc(questionChoices.position));
      if (choices.length < 2) continue;
      base.choix = choices.map((c) => ({ texte: c.label, correct: c.isCorrect }));
    } else {
      const answers = await db
        .select({ value: questionOpenAnswers.value })
        .from(questionOpenAnswers)
        .where(eq(questionOpenAnswers.questionId, row.id));
      if (answers.length === 0) continue;
      base.reponses = answers.map((a) => a.value);
    }
    if (row.explanation) base.explication = row.explanation;
    exported.push(base);
  }

  const previous = JSON.parse(readFileSync(FILE, "utf-8")) as {
    questions: Exported[];
  } & Record<string, unknown>;
  const before = new Map(previous.questions.map((q) => [q.enonce, canonical(q)]));
  const after = new Map(exported.map((q) => [q.enonce, canonical(q)]));

  const added = [...after.keys()].filter((k) => !before.has(k));
  const removed = [...before.keys()].filter((k) => !after.has(k));
  const changed = [...after.entries()]
    .filter(([k, v]) => before.has(k) && before.get(k) !== v)
    .map(([k]) => k);

  console.log(
    `[info] database ${exported.length} · file ${previous.questions.length} — ` +
      `+${added.length} / -${removed.length} / ~${changed.length}`,
  );
  for (const k of changed.slice(0, 15)) console.log(`   modifiée en base : ${k}`);
  for (const k of removed.slice(0, 10)) console.log(`   absente de la base : ${k}`);

  if (check) {
    const drift = added.length + removed.length + changed.length;
    console.log(
      drift === 0
        ? "[ok]   file matches the database"
        : `[warn] ${drift} differences — run without --check to realign`,
    );
    client.close();
    process.exit(drift === 0 ? 0 : 1);
  }

  const { questions: _drop, ...meta } = previous;
  const header = Object.entries({ ...meta, _exported_at: new Date().toISOString().slice(0, 10) })
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(",\n");
  const lines = exported.map((q) => `    ${canonical(q)}`).join(",\n");
  writeFileSync(FILE, `{\n${header},\n  "questions": [\n${lines}\n  ]\n}\n`);
  console.log(JSON.stringify({ event: "export_questions_complete", exported: exported.length }));
  client.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
